import * as z from "zod";

export const PostModel = z.object({
  /**
   * The unique identifier for the post
   * @default {Generated by database}
   */
  id: z.string().uuid(),
  /**
   * A brief title that describes the contents of the post
   */
  title: z.coerce.string().max(255, { message: "The title must be shorter than 256 characters" }),
  /**
   * The actual contents of the post.
   */
  contents: z.string().max(10240),
  /**
   * The post date
   */
  date: z.coerce.string({ required_error: "date is required" }).datetime(),
  /**
   * The file url
   */
  fileUrl: z.string({ invalid_type_error: "the file url is string" }).url().nullish(),
});
